//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sale_Id { get; set; }
        public string TicketNo { get; set; }
        public string TableName { get; set; }
        public string CustomerName { get; set; }
        public string OrderType { get; set; }
        public double Balance { get; set; }
        public string TicketNote { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string PhoneNumber { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> IsBillPending { get; set; }
        public int cashier_id { get; set; }
        public System.DateTime day { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public Nullable<double> RemainingBalance { get; set; }
        public int NumberOfPerson { get; set; }
        public double TAX { get; set; }
        public int IsRefund { get; set; }
        public string Cahier_Name { get; set; }
    }
}
