//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int ItemId { get; set; }
        public string itemName { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public double Quantity { get; set; }
        public double Total { get; set; }
        public string TicketNo { get; set; }
        public int RecordID { get; set; }
        public double Aed_Vat { get; set; }
        public double Aed_Vat_Amount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
