//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Tbl
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string ItemName { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
    }
}
