//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcription_Tbl
    {
        public int id { get; set; }
        public string SubcriptionKey { get; set; }
        public string UserTyoe { get; set; }
        public string ForeignId { get; set; }
    }
}
